/*Daily Coding Task Generated by ChatGPT - Task 2: Grocery Total Calculator

Task:
Ask the user for: Price of item 1, price of item 2, price of item 3, 
the sales tax rate as a decimal.

The program should print:
Subtotal before tax, tax amount, final total, whether the total is "within budget" or
"over budget."
The budget is: 50.00

Per ChatGPT: Do not use loops for this assignment (such as incrementing with i++);
Keep it simple.*/

#include <stdio.h>

int main(void) {
    double i1, i2, i3;
    double tax_rate;
    double subtotal;
    double tax;
    double final_total;

    printf("Enter the price of item 1: ");
    scanf("%lf", &i1);
    printf("Enter the price of item 2: ");
    scanf("%lf", &i2);
    printf("Enter the price of item 3: ");
    scanf("%lf", &i3);
    printf("Enter the tax rate as a percentage: ");
    scanf("%lf", &tax_rate);
    /*
    If ("Enter the tax as percentage: "): User is expected to type a whole number like 7
    If ("Enter the tax as a decimal: "): User is expected to write 0.07
    */
    

    // Calculations
    subtotal = i1 + i2 + i3;
    printf("Subtotal: $%.2lf\n", subtotal);

    tax = subtotal * (tax_rate/100); 
    printf("Tax: $%.2lf\n", tax);
    /* You weren't sure how to calculate the tax at first (which needed to result in $2.54) 
    until you used a calculator to help you determine that its: 
    subtotal (which for this assignment it comes out to $36.25) 
    multiplied by (tax rate divided by 100) (which for this assigment its 7).
    $36.25 * (7/100) = $2.54 */

    final_total = subtotal + tax;
    printf("Final total: $%.2lf\n", final_total);

    if (final_total <= 50.00) {
        printf("Status: Within Budget\n");
    }
    else {
        printf("Status: Over Budget\n");
    }


    return 0;
}