/*
Daily Coding Task Generated by ChatGPT - Task 1: 3 Quiz Scores

Task:
Write a small program that asks for 3 quiz scores, then calculates 
total = score 1 + score 2 + score 3
average = total / 3

Per ChatGPT: Do not use loops for this assignment (such as incrementing with i++);
Keep it simple.

Per ChatGPT, Use:
"int" for the three scores
"int" for total
double for average
*/

#include <stdio.h>

int main(void) {
    int s1, s2, s3;
    int total;
    double average;

    printf("Enter quiz 1: ");
    scanf("%d", &s1);

    printf("Enter quiz 2: ");
    scanf("%d", &s2);

    printf("Enter quiz 3: ");
    scanf("%d", &s3);
    printf("\n");

    // Calculations
    total = s1 + s2 + s3;
    average = total / 3.0;

    printf("Total: %d\n", total);
    printf("Average: %.2lf\n", average);
    
    // If/else Statement for status:
    if (average >= 80) {
        printf("Status: Passing");
        printf("\n");
    }
    else {
        printf("Status: Needs Improvement");
        printf("\n");
    }


    return 0;
}

/*
Thoughts:
I was able to complete the the code independently and 
match the output that Chat GPT wanted.
The only thing I didn't like was that ChatGPT had already given me the calculation set up.
I wanted to be able to create those myself because I struggle with doing that. I asked
ChatGPT to update my daily tasks to where I need to create the calculations myself. 

Overall: Easy Task, Completed Code by myself without help, Matched ChatGPT Output.
*/